#!/bin/sh

# git-histogram
#
# Runs a script for every commit in a git repository
# 
# Example: git-histogram 'echo `flog -s app` `flog -s spec`'
#

for i in `ruby -e 'puts %x{git log}.grep(/^commit/).map {|line| line.gsub(/commit /, "").strip }.reverse'`
do
  git reset -q --hard $i
  eval $* $i
done
